config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    root 'pages#landingpage'
    get 'aboutus', to:'pages#aboutus'
    resources :articles
    resources :users, except:[:new]
    get 'signup', to:'users#new'
    get 'login' , to:'sessions#new'
    post 'login', to:'sessions#create'
    delete 'logout', to:'sessions#destroy'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user 
    validates :title , presence: true
    validates :description , presence: true
end 

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles , dependent: :destroy 
    validates :username , presence: true , length: {minimum: 4, maximum: 30}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email , presence: true , uniqueness: {case_sensitive: false}, length: { maximum: 80}, format: { with: VALID_EMAIL_REGEX} 

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user , :logged_in?
    def current_user
        if session[:user_id]
        @current_user ||= User.find(session[:user_id])
        end
    end 

    def logged_in?
        !!current_user
    end

    def is_logged_in?
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :logged_in? , except: [:index, :show]
    before_action :is_same? , only: [:update ,:destroy ,:edit]

    def show
        @article = Article.find(params[:id])
    end
    
    def index
        @articles = Article.all
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(params.require(:article).permit(:title , :description))
        @article.user = current_user
        if @article.save
            redirect_to article_path(@article)
        else
            flash[:danger] = "Error"
            render 'new'
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title , :description))
              redirect_to article_path(@article)
        else
            render 'edit'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private
    def is_same?
        @article = Article.find(params[:id])
        if current_user != @article.user 
            redirect_to articles_path
        end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    
    def landingpage
        if logged_in?
            redirect_to articles_path
        end
    end

    def aboutus
    end
    
end
 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
        
    end

    def create
        user = User.find_by(email: params[:user][:email].downcase)
        if(user && user.authenticate(params[:user][:password]))
            session[:user_id] = user.id
            redirect_to user
        else
            render 'new'
        end
    end

    def destroy
        session[:user_id] = nil 
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :is_same? , only: [:edit ,:update ,:destroy]
    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end 

    def create        
        @user = User.new(params.require(:user).permit(:username,:email,:password))
        if @user.save 
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(params.require(:user).permit(:username,:email,:password))
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    def destroy
        @user = User.find(params[:id])
        session[:user_id] = nil if !current_user.admin?
        @user.destroy
        redirect_to users_path
    end

    private
        def is_same?
            @user = User.find(params[:id])
            if current_user != @user and !current_user.admin?
                redirect_to users_path
            end
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def gravator_for(user,options ={ size: 100})
        email_address = user.email.downcase
        hash = Digest::MD5.hexdigest(email_address)
        size = options[:size]
        image_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
        image_tag(image_url, alt: user.username, class: "img-fluid rounded mx-auto d-block")
    end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, url: articles_path ,local: true do |data| %>
<p>
<%= data.label :title%>
<br>
<%= data.text_field :title%>
</p>
<p>
<%= data.label :description%>
<br>
<%= data.text_area :description%>
</p>
<p>
<%= data.submit%>
</p>
<%end%>

app/views/articles/edit.html.erb
<%= render 'shared/errors', obj: @article %>
<section class="h-100 gradient-custom-2">
    <div class="card container py-5 h-100"><h1 class="text-center">Edit Article </h1>
    <%=render 'form'%>
    </div>
</section>

app/views/articles/index.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
<h1 class="text-center">Display All Articles</h1>
<br>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
  <br>
    <%@articles.each do |article|%>
      <div class="card mb-3" style="width: 18rem;" >
        <div class="card-body">
          <h5 class="card-title text-truncate"><%=article.title%></h5>
          <h6 class="card-subtitle mb-2 text-muted">by - <%=link_to article.user.username,user_path(article.user)%></h6>
          <p class="card-text text-truncate"><%=article.description%></p>
        <%=link_to 'Show', article_path(article)%>
        <%if logged_in? and (current_user == article.user or current_user.admin?)%>
        <%=link_to 'Edit', edit_article_path(article)%>
        <%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
        </div>
      </div>
    <%end%>
<br>
<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @articles %>
    </div>
    <%= will_paginate @articles, :container => false %>
  </div>
  </div>
</section>

app/views/articles/new.html.erb
<%= render 'shared/errors', obj: @article %>
<section class="h-100 gradient-custom-2">
    <div class="card container py-5 h-100"><h1 class="text-center">Create New Article </h1>
    <%=render 'form'%>
    </div>
</section>

app/views/articles/show.html.erb
<h1 class="text-center">This is show page</h1>
<h2>title: <%=@article.title%> </h2>
<h2>description: <%=@article.description%> </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>TesApp</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">


    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha384-6D+8rVUMYaLp8/A+UaO6TWfv1AH7x1qoStQFqQzKbLQ/lOyL9aI1zJv9zzTjp5B1" crossorigin="anonymous"></script>
<script src="https://unpkg.com/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js" integrity="sha384-2anHZi3qsjvV8ngKOTxSNPyi7ykTC6TnT6LbI6iAmS6DZazf8tLQ2BnDf7V5mmEo" crossorigin="anonymous"></script>

      <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Home", root_path, class: "navbar-brand"%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
          <%= link_to "Articles", articles_path, class: "nav-link"%>
      </li>
      <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link"%>
      </li>
      <%if logged_in?%>
        <li class="nav-item">
          <%= link_to "Create Article", new_article_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Profile[#{current_user.username}]", user_path(current_user), class: "nav-link" %>
      </li>
      <li class="nav-item">
          <%= button_to "Logout", logout_path, class: "nav-link", method: :delete %>
      </li>
      <% else %>
      <li class="nav-item">
          <%= link_to "SignUp", signup_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link"%>
      </li>
      <%end%>
    </ul>
  </div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/pages/aboutus.html.erb
<h1>Learn more about us</h1>

app/views/pages/landingpage.html.erb
<h1 class="text-center">This is the home page</h1>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
        <h2>
            following errors occured during the process:
        </h2>
        <div>
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
        </div>
<% end %>

app/views/users/edit.html.erb
<%= render 'shared/errors', obj: @user %>
<section class="h-100 gradient-custom-2">
  <div class=" card mgb-5 container py-5 h-100"><h1 class="text-center">This is Edit Page  </h1>
    <%= form_with(model: @user) do |data| %>
        <p>
        <%= data.label :username%>
        <br>
        <%= data.text_field :username%>
        </p>
        <p>
        <%= data.label :email%>
        <br>
        <%= data.text_field :email%>
        </p>
        <p>
        <%= data.label :password%>
        <br>
        <%= data.text_field :password%>
        </p>
        <p>
        <%= data.submit %>
        </p>
    <%end%>
  </div>
</section>

app/views/users/index.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100"><h1 class="text-center">Show all Users</h1>
        <%@users.each do |user|%>
            <div class="card mgb" style="width: 18rem;">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item"><%=user.username%></li>
                    <li class="list-group-item"><%=user.email%></li>
                    <li class="list-group-item">
                    <%=link_to 'Show', user_path(user)%>
                        <%if logged_in? and (current_user == user or current_user.admin?)%>
                            <%=link_to 'Edit', edit_user_path(user)%>
                            <%= button_to 'Delete', user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%end%>
                    </li>
                </ul>
            </div>
        <%end%>
    </table>
  </div>
</section>

app/views/users/new.html.erb
<%= render 'shared/errors', obj: @user %>


<section class="h-100 gradient-custom-2">
  <div class="card container py-5 h-100"><h1 class="text-center">SignUp Here  </h1>
        <%= form_with scope: :user, url: users_path ,local: true do |data| %>
        <p>
        <%= data.label :username%>
        <br>
        <%= data.text_field :username%>
        </p>
        <p>
        <%= data.label :email%>
        <br>
        <%= data.text_field :email%>
        </p>
        <p>
        <%= data.label :password%>
        <br>
        <%= data.text_field :password%>
        </p>
        <p>
        <%= data.submit%>
        </p>
        <%end%>
    </table>
  </div>
</section>

app/views/users/show.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-9 col-xl-7">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-color: #000; height:200px;">
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
              <%=gravator_for  @user %>
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h5><%=@user.username%></h5>
              <h5>User Articles - <%=@user.articles.length%></h5>
            </div>
            
          </div>
          <div class="p-4 text-black" style="background-color: #f8f9fa;">
            <div class="d-flex justify-content-end text-center py-1">
              <div>
              <%if logged_in? and @user == current_user%>
                <p class="mb-1 h5"><%= link_to 'Edit Profile', edit_user_path(@user) , class: "text-center"%></p>
              </div>
              <div class="px-3">
                <%= button_to 'Delete User Profile', user_path(current_user) ,class: "text-center text-danger", method: :delete ,data: { confirm: "Are You Sure?"}%>
              </div>
              <%end%>
            </div>
          </div>
          <div class="card-body p-4 text-black">
            <div class="d-flex justify-content-between align-items-center mb-4">
              
            <div class="row g-2">
                <%@user.articles.each do |article|%>
                    <div class="card mr-3" style="width: 18rem;">
                        <div class="card-body">
                        <h5 class="card-title"><%=article.title%></h5>
                        <h6 class="card-subtitle mb-2 text-muted text-truncate">by - <%=link_to article.user.username,user_path(article.user)%></h6>
                        <p class="card-text text-truncate"><%=article.description%></p>
                        <%=link_to 'Show', article_path(article)%>
                        <%if logged_in? and (current_user == article.user or current_user.admin?)%>
                        <%=link_to 'Edit', edit_article_path(article)%>
                        <%= button_to 'Delete', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
                        <%end%>
                        Joined <%=time_ago_in_words(article.created_at) %>
                        </div>
                    </div>
                <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>